# Generated by Django 2.0 on 2018-07-26 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premier_log',
            old_name='demand_type',
            new_name='type',
        ),
    ]
