# Generated by Django 2.0 on 2018-07-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0002_auto_20180726_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premier_log',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
