# Generated by Django 2.0 on 2018-07-26 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0003_auto_20180726_0852'),
    ]

    operations = [
    ]
