# Generated by Django 2.0 on 2018-07-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0004_auto_20180726_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premier_log',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
