# Generated by Django 2.0 on 2018-07-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0005_auto_20180726_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='premier_log_refined',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_id', models.CharField(blank=True, max_length=32, null=True)),
                ('client', models.CharField(blank=True, max_length=32, null=True)),
                ('type', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(max_length=8)),
                ('date_generated', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='premier_log',
        ),
    ]
