# Generated by Django 2.0 on 2018-07-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0006_auto_20180726_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='premier_log_refined',
            name='status_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='premier_log_refined',
            name='date_generated',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
