# Generated by Django 2.0 on 2018-07-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0007_auto_20180726_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premier_log_refined',
            name='date_generated',
            field=models.DateField(blank=True, max_length=32, null=True),
        ),
    ]
