# Generated by Django 2.0 on 2018-08-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0008_auto_20180727_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='entry_journals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debit_glaccount', models.CharField(max_length=20)),
                ('debit_branch', models.CharField(max_length=20)),
                ('credit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit_glaccount', models.CharField(max_length=20)),
                ('credit_branch', models.CharField(max_length=20)),
                ('entry_date', models.DateField(blank=True, max_length=32, null=True)),
                ('notes', models.CharField(max_length=200)),
            ],
        ),
    ]
