# Generated by Django 2.0 on 2018-08-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0009_entry_journals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry_journals',
            name='credit_glaccount',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='entry_journals',
            name='debit_glaccount',
            field=models.CharField(max_length=200),
        ),
    ]
