# Generated by Django 2.0 on 2018-08-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0010_auto_20180810_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry_journals',
            name='credit_glaccount',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='entry_journals',
            name='debit_glaccount',
            field=models.CharField(max_length=32),
        ),
    ]
