# Generated by Django 2.0 on 2018-08-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0012_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gl_accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoded_key', models.CharField(max_length=255)),
                ('glCode', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
