# Generated by Django 2.0 on 2018-08-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0013_gl_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry_journals',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
