# Generated by Django 2.0 on 2018-08-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0014_entry_journals_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry_journals',
            name='debit_branch',
            field=models.CharField(max_length=255),
        ),
    ]
