# Generated by Django 2.0 on 2018-08-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0015_auto_20180815_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry_journals',
            name='credit_branch',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='entry_journals',
            name='notes',
            field=models.CharField(max_length=255),
        ),
    ]
